branch-defaults:
  default:
    environment: assignment7env
global:
  application_name: MyApp
  branch: null
  default_ec2_keyname: assignment4
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
